### ISSUE TITLE
Add best case studies to Hg Foundation deck

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#1036]
### Background

We've progressed to the second stage of Hg Foundation grant, now we need to send some case studies.

### Acceptance criteria

- [x] @alecmccrindle to choose some great ones and add them to [slide 21 ](https://docs.google.com/presentation/d/1HQORculFA42tqu8jlWM0ehAGu-_3D6qR/edit#slide=id.p21)

### Owner

alec

### Stakeholder

Liliana and Claire

### Approver

Liliana and Claire

**Comment by alecmccrindle** [comment]
Sharing comment from the deck here too.

"I'd like to add video - Deago and Seraphine, can add others if needed. 

Can you check if video is okay and also, if they have a limit of case studies? I don't think we'll share more than 4, maybe two videos and two written ones?

The stories would be embedded in the deck (videos and written stories)."

**Comment by lilianabermudes** [comment]
Their answer: Video case studies very welcome and I’d say 2-3 is great – where they can show diversity too would be brilliant

**Comment by alecmccrindle** [comment]
I've added three videos, 2 x stories and the recent video that features several testimonials explaining why the CYF programme helps you get ready for the world of work. 

What are my risks with the videos?

- The descriptions are geared to social media, are they right for this pitch? Feel free to adjust.
- The third video features quotes from Deago and Seraphine which are featured in the first two videos. I don't think repeating them is a big issue, but letting you know in case you disagree. While testimonials in the third video are focused on explains our methods instead of personal journies, but, the clips also sometimes quite personal, which is why I think it works here.  

I suggest you watch all three in a row to make a determination?

I can add written stories too, but hopefully this works?

**Comment by ClaireBickley** [comment]
thanks Alec, I think we send to Hg and see if they have any feedback, they have been great on this front so far
