### ISSUE TITLE
Rewrite complaints procedure

### ISSUE THREAD

**Issue by ClaireBickley** [CodeYourFuture/CYF-Staff-Tickets#116]
doc started with comments on current process 
https://docs.google.com/document/d/1qy6TrpibTh7G_LTgT9ZuE0-6SnEEZ-_iexnMryM79wc/edit

**Comment by SallyMcGrath** [comment]
Is this done @ClaireBickley

**Comment by SallyMcGrath** [comment]
@ClaireBickley 

If this is a small high priority task it should be done. If it's not small, update the size estimate. (I think you usually spend many many hours on these rewrites?). If it's not high priority, update this.

Either way, don't leave things in progress for months because that's not progress. ❤ 😉

**Comment by ClaireBickley** [comment]
yes, this shouldn't have been marked as small 😆 I'll change the priority too
I need to get better at using Github boards!

**Comment by kfklein15** [comment]
Has this been done? It says in review :)

**Comment by lilianabermudes** [comment]
@alecmccrindle and @ClaireBickley maybe we need a new ticket?
