### ISSUE TITLE
Create form for collective job search and onboard trainees

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/CYF-Staff-Tickets#15]
Create a form for trainees/grads to submit their job research + prioritise contacts list for volunteers & team

Resources
SA Startup list - https://docs.google.com/spreadsheets/d/1ckzQlkQ-NIGEf02apVzHVuIui4psA0InmcQl25dQFpg/edit#gid=1964032918
WM Companies - https://docs.google.com/spreadsheets/d/1ZIPWqzjar3NA-jP50MfCKBHcF8oPCkJz/edit#gid=366149316
We Find Jobs Together - https://docs.google.com/spreadsheets/d/1QX7xLwBCsJQYWKeFwhHJ_Rd8os9mzqcL5QsmVH6bZ3k/edit#gid=1665590378

**Comment by Barny-6** [comment]
New Form here - https://docs.google.com/forms/d/1QhVXIEoQycWe2xbYIRmlWzX9gArPt48W6S7SXwLfbtw/edit

@gbencci please take a look and advise on any other category that should be included for prioritisation

**Comment by gbencci** [comment]
@Barny-6, some comments:
- it feels quite long
- i would generalise the stack a bit more.. be less specific the Mongo ones (why do we care so much about Mongo?), use more our own experience on how we divide the roles: FE, FS, Data, QA, React, .NET.. something like that
- Test it with a few company entries, get a small number of trainees and grads to pass the data through the form.

I would see the form as an entry point, but later people can add more things in the spreadsheet itself, otherwise people would struggle completing it

**Comment by gbencci** [comment]
@Barny-6 do you need anything else for this ticket?
I would create a new one for the implementation in each region

**Comment by gbencci** [comment]
@Barny-6 if this is ready, please close it and open a new one about implementing it in WM, NW and CPT.
