### ISSUE TITLE
Move CYF London Storage to BIR

### ISSUE THREAD

**Issue by lilianabermudes** [CodeYourFuture/CYF-Staff-Tickets#209]
- Check options --> G shared a link on Slack

**Comment by haldenb** [comment]
Go to space

Call Van

Co-ordinate arrival with Claire

**Comment by emcglackenr1** [comment]
Should Scotland storage also be moved?

**Comment by lilianabermudes** [comment]
Hi @emcglackenr1 can you please remind us where is it and how much we're paying?

**Comment by MattCFry** [comment]
Before anything is moved, we need a FULL INVENTORY.

- Any laptops need: Make, Model, Serial Number and condition (working, broken, etc)

**Comment by SallyMcGrath** [comment]
This is a large blocker to throw on "before anything is moved". Are you sure it is necessary to prevent moving, @MattCFry ?

Thinking about the course you are doing on Lean, how else could you think about this?

**Comment by MattCFry** [comment]
Still need to start the lean part of the track. Don't feel confident about finding the answer you are looking for yet.

Logistically speaking, if the van arrives with laptops and furniture (as suggested by G), we may be unable to fit everything in our storage. Halden and I are not equipped to manage our account with the storage providers and organise another unit, especially with a van waiting outside.

It's not required for physically moving. I feel this needs to be done some days in advance so that we are prepared to accept everything.

**Comment by SallyMcGrath** [comment]
So let's identify the part you need. I think we can agree that knowing, for example, the serial number of every laptop will not materially affect the size of either storage space or the volume of the equipment. 

It sounds like you need to know:

1. How much space you have available
2. How many things Halden expects to send

Is that right?

**Comment by SallyMcGrath** [comment]
@haldenb is this really in progress?

**Comment by haldenb** [comment]
Spoke to German and we will keep the storage in London Let me close this for now
