### ISSUE TITLE
Review and edit wording for CYF+ leaflet

### ISSUE THREAD

**Issue by gbencci** [CodeYourFuture/CYF-Staff-Tickets#239]
I have created a first draft for the CYF+ leaflet. What do you think of the wording? Would you add anything? This program is very difficult to explain in non-technical terms, so I'm having the top sections as not-technical and the other one is

Docs version for edits:
https://docs.google.com/document/d/1U8AMRkhhaLVqqHC48HAW-Gnm5GsCTtuxr5Hsf2-aluU/edit

https://www.figma.com/file/0niiYqGBfCUxfizyKbgJnV/CYF-Marketing-material?type=design&node-id=3271-62&mode=design&t=gG8FPpedkL0dzLdC-0

Later I'll add some clearer CTA, but want us to agree on the wording. Thanks!

**Comment by gbencci** [comment]
Created a docs version: https://docs.google.com/document/d/1U8AMRkhhaLVqqHC48HAW-Gnm5GsCTtuxr5Hsf2-aluU/edit

**Comment by SallyMcGrath** [comment]
Natrina's notes are strong I think.

PS  - she removed it already but it's either Golang or Go, never Go language. (One of those strange shibboleths)

**Comment by gbencci** [comment]
@SallyMcGrath Natrina's comments are good for creating a social impact 1-pager for CEOs. I'm trying also to build a technical version of the 1-pager. I reviewed the transcripts from the call, but they are very inaccurate, so I'll ask you here a series of questions and try to write something out of it:

- What's the difference between Systems Engineering and DevOps?
- How else could
- What kind of skills is the program achieving?
- How else could the curriculum evolve?
- In what ways is this not just about SRE role?

**Comment by SallyMcGrath** [comment]
What's the difference between Systems Engineering and DevOps?

We chose to focus on systems and engineering, a sort of mid-position between ops and swe, focusing on distributed systems. In the industry, there are two main philosophies of systems engineering: SRE and DevOps. Both come from ops background and they are closely related. Both are about bringing engineering principles, like automation, efficiency, scale, and formal reasoning, to ops and infra work.

The [DevOps Culture](https://www.atlassian.com/team-playbook/examples/devops-culture) is really applying Agile principles of putting ops in the same team as devs, so they create a shared culture of planning, building, testing, and shipping code in a tight iterative loop. These are product-led methods you will be familiar with. That's the philosophy; the reality/diffusion of this idea is basically ops and config (even lots of point and click automation thanks to Cloud providers) work but you also have to code, mainly infrastructure as code.  The Mentor project offered a DevOpsy role.

[The SRE mindset](https://www.cortex.io/post/the-power-of-adopting-an-sre-mindset) doesn't have much to say about team formation or Agile, it's much more about specific practices, and habits of thought, that are useful for building reliable distributed systems. When we talked about creating encounters with these ideas, these are the habits we sought to introduce. So, who owns a service, how is it documented, how are we monitoring it (and are those alerts actually useful), what happens when it fails and how do we learn from this failure. The broken sandboxes, Buggy App project, and[ Kafka Cron](https://systems.codeyourfuture.io/projects/kafka-cron/), Troubleshooting primers all  addressed these ideas. The other projects explored ideas like "how do we automate" and "how does this scale", which are also key parts of the SRE mindset. 

The shared knowledge base is stuff like Linux, pipelines, containers, distributed systems (RPCs, sharding, replication, leader-election...) and then probably provisioning?

**Comment by SallyMcGrath** [comment]
How else could the curriculum evolve?

The goal is to have [each partner contribute three or more projects](https://docs.google.com/document/d/1IhmCvIzbHGOYptu6OA8QryfmyP_9mgVZH5wAp__97YE/edit?usp=sharing) that prepare the trainee for their context.  We work with the engineers to develop their ideas into solid projects and they contribute them to the open source repo. 

For example, Grafana might join and build a fun project around [Grafana Incident](https://grafana.com/products/cloud/incident/), where the trainees experience an outage and go through the whole process of[ Incident Management](https://www.atlassian.com/incident-management#the-importance-of-incident-management).  

Or Twilio might join and develop something which develops the skills they need with Kubernetes. 

By developing these public student projects, not only can partners get a well-prepared new SRE joining their team and fitting like a glove, but they can also seed the world with the skills they need inside their business.

**Comment by SallyMcGrath** [comment]
I guess a piece we all assumed but isn't quite explicit here is that in this kind of large scale systems engineering, it's not enough to learn tools or complete tutorials, you need to be mentored into a way of thinking and working that can handle this kind of complexity. It's theoretical and practical.
