### ISSUE TITLE
Speaking at external events

### ISSUE THREAD

**Issue by alecmccrindle** [CodeYourFuture/CYF-Staff-Tickets#479]
### Background

Speaking at external events has driven good partnership results for CYF. Also, volunteers. We want to connect with key tech events and make a case to speak there. 

Note: where folks don't offer speaking slots, what are our asks?

[Pitch is here](https://docs.google.com/document/d/13M-5SmB3p8wZJEo8hvXtydsGRZGJkLTpp-QXgaILjTs/edit).

### Acceptance criteria

- [x] Make list
- [x] Write brief
- [x] Finalise brief
- [x] Email organisers for upcoming events (6 - 9 months) [next sprint]
- [x] Research new events
- [x] Update list
- [x] Contact organisers for new events

### Owner

@alecmccrindle

### Stakeholder

@MarianaVazquezCYF

### Approver

@gbencci

**Comment by MarianaVazquezCYF** [comment]
Hello, the Manchester students have helped us to research all the events!! we have a lot! and due to capacity we couldn't message the people for the February events, the list is here: 

My suggestion is that we give the pitch and the community mail to the manchester students and they can send those emails? Obviously adding us to the thread! is this possible ?

https://docs.google.com/spreadsheets/d/14nFnWS6nC_n-r0T-sf6mSRD_cUy7AQFnRyhWQCWFSOA/edit#gid=199855918

**Comment by MarianaVazquezCYF** [comment]
This ticket is actually a milestone! I created this small ticket with the conferences I will message this sprint: https://github.com/CodeYourFuture/CYF-Staff-Tickets/issues/638

**Comment by MarianaVazquezCYF** [comment]
This is the main ticket we are working on @Barny-6
