### ISSUE TITLE
Approval of Sheffield Chapter

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#482]
### Background

We have done a plan to launch Sheffield Chapter, but we need it to be given the green light.

### Acceptance criteria

- Read the [Sheffield Launch Strategy](https://docs.google.com/document/d/1Pfzt1S2gQ7YHRXnyjB1FaxIFLSPaOeEZfXixwlFlm3I/edit)
- Align any open questions
- Get green light

### Owner
@MarianaVazquezCYF 

### Stakeholder
@alecmccrindle @Dedekind561 @kfklein15 @lilianabermudes 

### Approver
@SallyMcGrath @gbencci

**Comment by gbencci** [comment]
@SallyMcGrath I have added to the doc a small set of proposals. Please read them and give me your thoughts. Everything is up for discussion; this is just as input. This are of growth will become critical, so we need to be crystal clear among ourselves..

**Comment by SallyMcGrath** [comment]
I'm pretty happy with those proposals. They seem like solid improvements to me. I think taking this project as a learning and development opportunity for the team is also wise. When we do open up London again we will need to be in a good place, confident in what we are doing. I'd rather practice with Sheffield than London, just because of the scale and complexity of London. 

I really want us to emerge stronger and better from this terrible year, and I think this is an opportunity.
