### ISSUE TITLE
Maketing materials for tech leaders strategy

### ISSUE THREAD

**Issue by MarianaVazquezCYF** [CodeYourFuture/CYF-Staff-Tickets#508]
Talking with Sally, she said she would like to have flyers or marketing materials to invite her network and in this way more people could invite more people! 

Therefore, could we please have a proposal and in that way she can start sharing them with her network? thanks!

**Comment by kfklein15** [comment]
Is this something that must be done this sprint? If not, can you move it to the next one, and we can describe the ticket better?

**Comment by alecmccrindle** [comment]
I'm going to move this to the next sprint. 

With the uncertainly around Portfolio Saturdays, I will wait until we know what

@MarianaVazquezCYF - if we get confirmation from anyone about Portfolio Saturdays, I will make this material for Sally and share it with her while you are on holiday.

**Comment by alecmccrindle** [comment]
I made this for feedback, once we get clarity on which events we want to run. 

[Deck to invite leaders to speak at CYF](https://docs.google.com/presentation/d/1qBbvr1AG6hviU52sFYNWrQV9vLR8mnwDizp8LEYof60/edit#slide=id.p7)

**Comment by alecmccrindle** [comment]
Spoke to @MarianaVazquezCYF - moving the next steps into the next sprint. 

- [ ] Speak to Sally about the material to invite other folks
- [ ] Work with @MarianaVazquezCYF to determine dates for other events - and what those events are

**Comment by alecmccrindle** [comment]
Hello @SallyMcGrath - can you [review and give feedback on this tech leader events invite / marketing material](https://docs.google.com/presentation/d/1qBbvr1AG6hviU52sFYNWrQV9vLR8mnwDizp8LEYof60/edit#slide=id.g2b8f37048fe_0_9) to send to your contacts?

Note: still finalising dates. That should be ready tomorrow/Monday.

**Comment by SallyMcGrath** [comment]
Hi btw if possible assign me to things on here with a deadline instead of atting me then  DMing me. 

Everyone asking me over and over in multiple venues is creating an unmanageable volume of messages so is counterproductive (for you!) if you need my attention. If I could get the ~800 messages a day down to even just 400 by reducing duplicates, I could answer your questions more easily.

I have looked at the slides - thanks for these! In general pretty good! I showed them to a couple of tech people here and here's what they said:

It's a lot of slides - could there be fewer? 6 slides at the beginning just to explain who CYF are before the ask comes seems like a lot of up front explanation. 

Everyone looks very serious in slides 9 and 10 - a bit forbidding!

The salary was not an uplifting number to see - consider the target audience of tech leaders - I had to contextualise it  - maybe a different stat.

It's a bit hard to read the writing, especially on slide 10 and 12.

**Comment by alecmccrindle** [comment]
[Updated deck based on feedback](https://docs.google.com/presentation/d/1xBbfd0stzh0RKch7WMMA80se7Xf3uBQKYsd8CO1YbVg/edit#slide=id.g24451011dc4_0_0). Need to finalise events now

**Comment by kfklein15** [comment]
Future tickets should be per speaker with acceptance criteria: notify cohort funders/volunters, ask them to take photos, send location to speaker, update marketing materials, post on social media to inform about this
