### ISSUE TITLE
Mapping the Attendance Process

### ISSUE THREAD

**Issue by MattCFry** [CodeYourFuture/CYF-Staff-Tickets#553]
### Background

Some final projects provide an attendance system, and we want to investigate if one can be used.

The main difficulty of mapping processes is finding out the difference between what you think people do and what they actually do. Ask PROMs first, then ask who is actually in class (a volunteer or trainee :D). Usually, the answers are different.

### Acceptance criteria

- [x] Survey all region Proms and understand what is the intended method in all regions
- [ ] Map at low level all regional processes
- [ ] Present to programme team

### Owner

@mattcfry

### Stakeholder

@kfklein15, @CodeYourFuture/programme-managers

### Approver

@kfklein15

**Comment by emcglackenr1** [comment]
Brief intro to our main two methods, but we can discuss in more detail:

**Spreadsheet that volunteers filled in**
Pro:
Instantly easy to track attendance and communicate it.
Con: 
Engagement was on and off. Sometimes I'd just do it myself. Either because I was there, or after asking volunteers who was. With a good spreadsheet set up it takes only a few minutes, so not a huge admin burden.

**Physical sign in sheet**
Was introduced by a venue for fire safety. We then continued to use it as an attendance sheet. 

Pros:
High engagement. Trainees filled it in for themselves and passed it around. Volunteers often did. Community took responsibility.

Cons:
Volunteers sometimes didn't fill it in as they thought of it as being for trainees. For many purposes, include venue booking logistics, it's good to know everyone who attended. 
Sometimes it got physically lost by community members after class. To solve this, a photo would be added to Slack / GDrive. 
Physical sheet or a photo of it had to be digitised at some point. This meant that someone would have to go through these sheet images to digitise it if attendance was being tracked.

**Comment by MattCFry** [comment]
@haldenb @ShaunCYFSA, when you guys get a second, could you give some info on the attendance process in your regions? Not urgent at all

**Comment by haldenb** [comment]
Attendance process was a continual struggle:

- Tried printing off a list of names and trainees physically ticked it off when they came in but it was inaccurate
- Tried giving it to volunteers but they did not know all of the names (huge classes never again :P)
- During FP Volunteers reported if a member of their group was missing for a weekend 
- During PF module we tried to include it all on the same open spreadsheet that trainees had access to - the module lead did a pretty good job of recording it when she was there (https://docs.google.com/spreadsheets/d/1olclpT0ANIvSeSRSvA2RMp3v4nZJbNUiRykeDJcUUrU/edit#gid=1779254254))

**Comment by ShaunCYFSA** [comment]
I used the tracker to update attendance.
If I could not attend the session, a volunteer (PD or Tech) would update the attendance tab in the tracker.
During FP, we used the tracker as well. Trainees informed us and their team if they could not attend, and we would make a note.
