### ISSUE TITLE
Change Google Classroom to Github

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#74]
https://github.com/CodeYourFuture/HTML-CSS-Coursework-TEST

https://github.com/CodeYourFuture/HTML-CSS-Coursework-TEST/issues

**Comment by kfklein15** [comment]
Asked to change the wording "point" and to invert the project assign vs priority/size

**Comment by kfklein15** [comment]
Another question: what is the "Link to the coursework"? I am not sure it is clear what link is supposed to be used here.

**Comment by SallyMcGrath** [comment]
Here's an example https://github.com/CodeYourFuture/HTML-CSS-Coursework-TEST/issues/3 @kfklein15

**Comment by kfklein15** [comment]
[Briefing](https://docs.google.com/document/d/1zFx-RscN4Iy9hhLKPm_wZUxsTqPq7CNR4ZZp566b2uI/edit#) for the extra development needed

**Comment by kfklein15** [comment]
Can we close this, since we are already piloting it, @SallyMcGrath ?

**Comment by SallyMcGrath** [comment]
I didn't make this ticket - I don't think it's mine?

**Comment by SallyMcGrath** [comment]
But PD hasn't added its tickets to the board so you still have some work to do

**Comment by kfklein15** [comment]
Esma created at least one. When you say it's not on the board, which board are you talking about, @SallyMcGrath ?

**Comment by SallyMcGrath** [comment]
BTW if you need me to help you with this, book a call and we can power through adding everything. Me and Mitch have already done loads of the other modules since last we spoke.

- Fundamentals : https://github.com/orgs/CodeYourFuture/projects/88/views/2
- HTML: https://github.com/orgs/CodeYourFuture/projects/87/views/4
- JS3 : https://github.com/orgs/CodeYourFuture/projects/83/views/4
- Node: https://github.com/orgs/CodeYourFuture/projects/85/views/4
- Databases: https://github.com/orgs/CodeYourFuture/projects/89

We're working on JS1 and JS2 now

**Comment by kfklein15** [comment]
I thought we were doing a pilot only, but from your last message, you were
moving all coursework to Gthub. Can you confirm this so that I can update
the PD Syllabus team on it? Thanks :)

**Comment by SallyMcGrath** [comment]
We are doing a pilot, in JS3. I'm talking here about JS3, on which there is only 1 piece of PD coursework.

Me and Mitch are getting ahead on the other modules because so far it's looking like the right option and we have to do a lot of other syllabus revisions anyway. But this conversation  is about JS3, which starts in a week. Do you need me to do it?

https://github.com/CodeYourFuture/Module-JS3/issues
https://github.com/orgs/CodeYourFuture/projects/83/views/4

**Comment by kfklein15** [comment]
Cool, thanks. No need for you to do anything, just wanted to make sure I didn't misunderstand it :)
