### ISSUE TITLE
 Follow up Email to Organisations we haven't heard from 

### ISSUE THREAD

**Issue by MattCFry** [CodeYourFuture/CYF-Staff-Tickets#861]
### Background

Related to #828 and #860. We want to reengage with organisations we have contacted but have not replied.

### Acceptance criteria

- [x] Send 1st no reply email follow up to all orgs who have not replied to us from #828 

### Owner

@mattcfry

### Stakeholder

-

### Approver

@mattcfry

**Comment by MattCFry** [comment]
Blocked - https://support.google.com/a/thread/203167266/multisend-not-working?hl=en

**Comment by emcglackenr1** [comment]
Hey Matt, we could put a hold on this (since it is blocked anyway due to technical issues) until after we chat tomorrow morning ? I know we discussed changing priorities because there is no longer a venue, but I was thinking:

Myself and Halden had already discussed follow up phonecalls, planned with Lili and Mariana . Then we added it to the Kanban / booked it into our calendars. Amy and I had discussed waiting to follow up via email when she was back, and we can get her input tomorrow on how to do the follow up.

**Comment by MattCFry** [comment]
Unblocked! 🥳 thank you @AmyCYF! Assigning you as you were super helpful
