### ISSUE TITLE
Brief for community safety project for next cohorts

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-Staff-Tickets#990]
Hey Alec, just on the safeguarding/community safety piece we spoke about. I asked Lili about adding to the job description for my cover. She isn't against it but wants to know more about what the time commitment would be. So for example, how many hours per week should be dedicated to this area?

I said there are 2 parts, the adhoc work that happens when a case is raised. This can be a little time or a long time, depending on the case. The other part is the ongoing work, that needs scoping, which is what you're working on.

So we left it as I'd update the JD with her recommendations and await your piece on the safeguarding work to be done and go from there.

**Comment by alecmccrindle** [comment]
Time per week on CoC and Safeguarding: 

9 x CoC cases since the start of 2021 = 3 per year. 
4 x Safeguarding cases recorded since 2022 = 1 per year. 

The deputy safeguarding lead handled most of the appeals on the CoC cases. 

Time estimate

- We're fairly efficient nowadays.
- I'd guess for a complex case it's up to 12 hours of of reading, calls and correspondence. There may be a timeline and write-up too. 
- Maybe 3-5 hours for a straightforward case. If we average it out, it's around 7 hours per case. 

So maybe around 4 days work a year.

**Comment by alecmccrindle** [comment]
Closing this ticket as I've also added thoughts to the JD.
